language: python
python:
- "3.6"
sudo: false

env:
  global:
  - BYOND_MAJOR="512"
  - BYOND_MINOR="1413"
  - ALL_MAPS="tgstation metaclub defficiency packedstation test_box test_tiny"
  matrix:
  - SCRIPT_TO_RUN="build_and_test_libvg.sh"
  - SCRIPT_TO_RUN="build_and_check_all_maps.sh"
  - SCRIPT_TO_RUN="build_and_test_dm.sh"

cache:
  directories:
  - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/libvg/target
  - $HOME/.cargo

addons:
  apt:
    packages:
    - libc6-i386
    - libgcc1:i386
    - libstdc++6:i386

install:
- pip install --user PyYaml beautifulsoup4 subprocess32 colorama -q

before_script:
- tools/travis/install-byond.sh

script:
- tools/travis/$SCRIPT_TO_RUN

notifications:
  irc:
    channels:
    - "irc.rizon.net#vgstation"
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - "Change view : %{compare_url}"
    - "Build details : %{build_url}"
